let genarray_of_array0: Array0.t<'a, 'b, 'c> => Genarray.t<'a, 'b, 'c>
let genarray_of_array1: Array1.t<'a, 'b, 'c> => Genarray.t<'a, 'b, 'c>
let genarray_of_array2: Array2.t<'a, 'b, 'c> => Genarray.t<'a, 'b, 'c>
let genarray_of_array3: Array3.t<'a, 'b, 'c> => Genarray.t<'a, 'b, 'c>

let array0_of_genarray: Genarray.t<'a, 'b, 'c> => Array0.t<'a, 'b, 'c>
let array1_of_genarray: Genarray.t<'a, 'b, 'c> => Array1.t<'a, 'b, 'c>
let array2_of_genarray: Genarray.t<'a, 'b, 'c> => Array2.t<'a, 'b, 'c>
let array3_of_genarray: Genarray.t<'a, 'b, 'c> => Array3.t<'a, 'b, 'c>
